eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: spring-cloud-provider-8001 #\u81EA\u5B9A\u4E49\u670D\u52A1\u540D\u79F0\u4FE1\u606F
    prefer-ip-address: true  #\u663E\u793A\u8BBF\u95EE\u8DEF\u5F84\u7684 ip \u5730\u5740
server:
  port: 8001
  servlet:
    context-path: /provider
spring:
  application:
    name: spring-cloud-provider-8001

